sudo: false
language: node_js
branches:
  only:
      - master
      - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - "node"
  - "lts/*"
before_install:
  - npm i -g npm@2
before_script:
  - npm prune
script:
  - npm run test
install: npm install
